[package]
name = "infrablockspace-statement-distribution"
description = "Statement Distribution Subsystem"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
infrablockspace-primitives = { path = "../../../primitives" }
sp-staking = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master", default-features = false }
sp-keystore = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
infrablockspace-node-subsystem = {path = "../../subsystem" }
infrablockspace-node-primitives = { path = "../../primitives" }
infrablockspace-node-subsystem-util = { path = "../../subsystem-util" }
infrablockspace-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.7.3"
indexmap = "1.9.1"
parity-scale-codec = { version = "3.3.0", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
fatality = "0.0.6"

[dev-dependencies]
infrablockspace-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-authority-discovery = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-keyring = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-core = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-keystore = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-tracing = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-keystore = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-network = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
futures-timer = "3.0.2"
infrablockspace-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
